### ISSUE TITLE
NoClassDefFoundError: org/hibernate/bytecode/internal/javassist/FieldHandler with hibernate 5.1

### ISSUE THREAD

**Issue by yorl1n** [FasterXML/jackson-datatype-hibernate#86]
I have just updated jackson-datatype-hibernate5 to the version 2.7.1 and hibernate to v. 5.1.0.Final
and get the error: java.lang.NoClassDefFoundError: org/hibernate/bytecode/internal/javassist/FieldHandler
As I can see from commit 
https://github.com/hibernate/hibernate-orm/commit/472f4ab9ef3ce3af2cb5805359345a1cec73ff3d

the file org.hibernate.bytecode.internal.javassist.FieldHandler was removed.

Here is stacktrace:

Caused by: java.lang.NoClassDefFoundError: org/hibernate/bytecode/internal/javassist/FieldHandler
        at com.fasterxml.jackson.datatype.hibernate5.HibernateAnnotationIntrospector.isIgnorableType(HibernateAnnotationIntrospector.java:82)
        at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.isIgnorableType(AnnotationIntrospectorPair.java:150)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.removeIgnorableTypes(BeanSerializerFactory.java:704)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:572)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:388)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:271)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:223)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:157)
        at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1215)
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1167)
        at com.fasterxml.jackson.databind.SerializerProvider._findExplicitUntypedSerializer(SerializerProvider.java:1136)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.hasSerializerFor(DefaultSerializerProvider.java:431)
        at com.fasterxml.jackson.databind.ObjectMapper.canSerialize(ObjectMapper.java:2611)

**Comment by cowtowncoder** [comment]
Thank you for reporting this. Looks like handling needs to be improved here. I assume 5.0.x of Hibernate still had this class... perhaps 5.1 has it moved to a different package.

**Comment by cowtowncoder** [comment]
Hmmh. Ok. So no replacement. I wish I knew whether handling is needed for 5.0.x itself either.
But I guess changing code to optionally include this may not be too bad. Would just be nice to know if it was fully obsolete so could remove.

**Comment by heruan** [comment]
Is this fixed in `2.7.1` or will it be in `2.7.2`?

**Comment by cowtowncoder** [comment]
@heruan It will be in 2.7.2.

**Comment by zhasulan** [comment]
I use HIBERNATE 5.2.4 and tried different versions of jackson-datatype-hibernate but the error is still present!

**Comment by yorl1n** [comment]
Do you use jackson-datatype-hibernate5 or jackson-datatype-hibernate. I use <hibernate-version>5.2.4.Final</hibernate-version> and <jackson-version>2.8.4</jackson-version> and everything works properly.

**Comment by zhasulan** [comment]
I just realized this, thank you!
